import SwiftUI
import UniformTypeIdentifiers

struct QuickStudyView: View {
    let initialDeckName: String?
    let initialNoteID: String?

    @State private var deckExport: DeckExport? = AppGroupStore.loadDeckExport()
    @State private var importing = false
    @State private var importError: String?

    private let preferredDecks = ["Chinese Grammar (汉语 语法)", "Neri's Chinese Course"]

    init(initialDeckName: String? = nil, initialNoteID: String? = nil) {
        self.initialDeckName = initialDeckName
        self.initialNoteID = initialNoteID
    }

    var body: some View {
        Group {
            if let export = deckExport,
               let target = deepLinkDeck(in: export) {
                DeckCardsView(deck: target, initialNoteID: initialNoteID)
            } else {
                deckList
            }
        }
        .navigationTitle(Brand.quickStudyChinese)
        .navigationBarTitleDisplayMode(.inline)
        .fileImporter(isPresented: $importing, allowedContentTypes: [.json]) { result in
            importDeck(result)
        }
        .alert("Import failed", isPresented: Binding(
            get: { importError != nil },
            set: { if !$0 { importError = nil } }
        )) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(importError ?? "Unknown error")
        }
    }

    private var deckList: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 3) {
                    Text(Brand.quickStudyChinese)
                        .font(.largeTitle.bold())
                    Text(Brand.quickStudyPinyin)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                    Text("Anki self-study stays separate from 汉语谈话 conversation memory.")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                        .padding(.top, 5)
                }
                .listRowInsets(EdgeInsets(top: 16, leading: 16, bottom: 12, trailing: 16))
            }

            if let export = deckExport {
                Section("Decks") {
                    ForEach(sortedDecks(export.decks)) { deck in
                        NavigationLink {
                            DeckCardsView(deck: deck, initialNoteID: nil)
                        } label: {
                            VStack(alignment: .leading, spacing: 4) {
                                Text(deck.name)
                                Text("\(deck.notes.count) notes")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                }
            } else {
                Section {
                    ContentUnavailableView(
                        "No Anki data imported",
                        systemImage: "square.and.arrow.down",
                        description: Text("Import anki-widget.json generated by the desktop exporter.")
                    )
                }
            }

            Section {
                Button {
                    importing = true
                } label: {
                    Label(deckExport == nil ? "Import Anki JSON" : "Replace imported Anki JSON", systemImage: "square.and.arrow.down")
                }
            }
        }
    }

    private func importDeck(_ result: Result<URL, Error>) {
        do {
            let url = try result.get()
            let access = url.startAccessingSecurityScopedResource()
            defer { if access { url.stopAccessingSecurityScopedResource() } }
            let data = try Data(contentsOf: url)
            try AppGroupStore.saveDeckExport(data: data)
            deckExport = AppGroupStore.loadDeckExport()
            importError = nil
        } catch {
            importError = error.localizedDescription
        }
    }

    private func deepLinkDeck(in export: DeckExport) -> Deck? {
        guard initialDeckName != nil || initialNoteID != nil else { return nil }

        if let initialDeckName,
           let deck = export.decks.first(where: { $0.name == initialDeckName }),
           initialNoteID == nil || deck.notes.contains(where: { $0.id == initialNoteID }) {
            return deck
        }

        if let initialNoteID {
            return export.decks.first(where: { deck in
                deck.notes.contains(where: { $0.id == initialNoteID })
            })
        }

        return nil
    }

    private func sortedDecks(_ decks: [Deck]) -> [Deck] {
        decks.sorted { lhs, rhs in
            let li = preferredDecks.firstIndex(of: lhs.name) ?? Int.max
            let ri = preferredDecks.firstIndex(of: rhs.name) ?? Int.max
            if li != ri { return li < ri }
            return lhs.name.localizedCaseInsensitiveCompare(rhs.name) == .orderedAscending
        }
    }
}

private struct DeckCardsView: View {
    let deck: Deck
    let initialNoteID: String?
    @State private var index: Int
    @State private var showingAnswer = true

    init(deck: Deck, initialNoteID: String?) {
        self.deck = deck
        self.initialNoteID = initialNoteID
        let initialIndex = initialNoteID.flatMap { id in deck.notes.firstIndex(where: { $0.id == id }) } ?? 0
        _index = State(initialValue: initialIndex)
    }

    var body: some View {
        VStack(spacing: 22) {
            if deck.notes.isEmpty {
                ContentUnavailableView("Empty deck", systemImage: "rectangle.stack")
            } else {
                let note = deck.notes[index]

                Spacer(minLength: 18)

                Text(note.hanzi)
                    .font(.system(size: 56, weight: .semibold, design: .rounded))
                    .minimumScaleFactor(0.55)
                    .multilineTextAlignment(.center)
                    .textSelection(.enabled)

                if let pinyin = note.pinyin {
                    Text(pinyin)
                        .font(.title3)
                        .foregroundStyle(.secondary)
                        .textSelection(.enabled)
                }

                if showingAnswer {
                    if let meaning = note.meaning {
                        Text(meaning)
                            .font(.title3)
                            .multilineTextAlignment(.center)
                            .textSelection(.enabled)
                    }

                    if let example = note.example {
                        Text(example)
                            .font(.body)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.top, 4)
                            .textSelection(.enabled)
                    }
                } else {
                    Button("Show answer") { showingAnswer = true }
                        .buttonStyle(.borderedProminent)
                }

                Spacer()

                HStack {
                    Button {
                        index = (index - 1 + deck.notes.count) % deck.notes.count
                        showingAnswer = true
                    } label: {
                        Label("Previous", systemImage: "chevron.left")
                    }
                    .buttonStyle(.bordered)

                    Spacer()

                    Button(showingAnswer ? "Hide" : "Reveal") {
                        showingAnswer.toggle()
                    }
                    .buttonStyle(.borderless)

                    Text("\(index + 1) / \(deck.notes.count)")
                        .font(.caption.monospacedDigit())
                        .foregroundStyle(.secondary)

                    Spacer()

                    Button {
                        index = (index + 1) % deck.notes.count
                        showingAnswer = true
                    } label: {
                        Label("Next", systemImage: "chevron.right")
                    }
                    .buttonStyle(.borderedProminent)
                }
            }
        }
        .padding()
        .navigationTitle(deck.name)
        .navigationBarTitleDisplayMode(.inline)
    }
}
